source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

gem 'rubocop', '~> 1.56', require: false
gem 'rubocop-performance', '~> 1.11', require: false
